/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank Candidates
         * @description Rank uploaded resumes against a job description.
         *
         *     Returns candidates sorted by composite score (semantic similarity +
         *     skill coverage + experience alignment). See /rank/stream for a version
         *     that reports progress while it works.
         */
        post: operations["rank_candidates_api_rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rank/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank Candidates Stream
         * @description Same as /rank, streamed as Server-Sent Events:
         *
         *     - `progress`: {"stage": "extracting" | "ranking" | "enriching" | "assessing", "done", "total"}
         *     - `result`: the RankResponse JSON (last event on success)
         *     - `error`: {"detail": "..."} (last event on failure)
         *
         *     Request validation errors are returned as normal HTTP errors before the stream starts.
         */
        post: operations["rank_candidates_stream_api_rank_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Resume
         * @description Extract contact information and skills from a single resume without ranking.
         *     Useful for quick candidate scans or pre-processing.
         */
        post: operations["extract_resume_api_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return current model status and Ollama availability.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_resume_api_extract_post */
        Body_extract_resume_api_extract_post: {
            /**
             * File
             * @description Single resume file (PDF, DOCX, TXT)
             */
            file: string;
        };
        /** Body_rank_candidates_api_rank_post */
        Body_rank_candidates_api_rank_post: {
            /**
             * Job Description
             * @description Full job description text
             */
            job_description: string;
            /**
             * Files
             * @description Resume files (PDF, DOCX, TXT)
             */
            files: string[];
            /** Top K */
            top_k?: number | null;
        };
        /** Body_rank_candidates_stream_api_rank_stream_post */
        Body_rank_candidates_stream_api_rank_stream_post: {
            /**
             * Job Description
             * @description Full job description text
             */
            job_description: string;
            /**
             * Files
             * @description Resume files (PDF, DOCX, TXT)
             */
            files: string[];
            /** Top K */
            top_k?: number | null;
        };
        /** CandidateResult */
        CandidateResult: {
            /** Rank */
            rank: number;
            /** Candidate Name */
            candidate_name: string;
            /** Filename */
            filename: string;
            /** Percentage Score */
            percentage_score: number;
            /** Composite Score */
            composite_score: number;
            /** Similarity Score */
            similarity_score: number;
            /** Semantic Score */
            semantic_score: number;
            /** Skill Coverage Score */
            skill_coverage_score: number | null;
            /** Experience Score */
            experience_score: number | null;
            /** Category */
            category: string;
            /** Category Emoji */
            category_emoji: string;
            /** Category Color */
            category_color: string;
            /** Matching Skills */
            matching_skills: string[];
            /** Fit Summary */
            fit_summary: string;
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Gaps
             * @default []
             */
            gaps: string[];
            /** Recommendation */
            recommendation?: ("Strong Yes" | "Yes" | "Maybe" | "No") | null;
            /**
             * Summary Source
             * @default template
             * @enum {string}
             */
            summary_source: "llm" | "template";
            contact: components["schemas"]["ContactInfo"];
        };
        /** ContactInfo */
        ContactInfo: {
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin */
            linkedin?: string | null;
            /** Github */
            github?: string | null;
            /** Location */
            location?: string | null;
            /** Website */
            website?: string | null;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Candidate Name */
            candidate_name: string;
            /** Skills */
            skills: string[];
            contact: components["schemas"]["ContactInfo"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Device */
            embedding_device: string;
            /** Ollama Available */
            ollama_available: boolean;
            /** Ollama Model */
            ollama_model: string;
            /** Summary Mode */
            summary_mode: string;
        };
        /** RankResponse */
        RankResponse: {
            /** Total Processed */
            total_processed: number;
            /** Total Duration Ms */
            total_duration_ms: number;
            /** Job Description */
            job_description: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rank_candidates_api_rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_rank_candidates_api_rank_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_candidates_stream_api_rank_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_rank_candidates_stream_api_rank_stream_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_resume_api_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_resume_api_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
